### ISSUE TITLE
About the meaning of cvf

### ISSUE THREAD

**Issue by nemoHy** [kai422/CoVOS#1]
Hi! Could you tell me the meaning of cvf in your code?
`cvf = decode_compressed_video(video)  # cvf: compressed video features`

I am confused with the code in line 106 to 114, decoder.py.
```
cvf["residual"] = cvf["residual"]-0.5
x_rescale = 0.25 * (mv_shape[0] / cvf["height"])
y_rescale = 0.25 * (mv_shape[1] / cvf["width"])
```
Thanks!

**Comment by kai422** [comment]
Hi nemoHy,

The value of the residual can be negative in the bitstream. Thus in the HEVC feature decoder, I offset the residuals extracted by +128 in order to store them in uint_8.  Here the residual is normalized.
The motion vectors decoded from HEVC bitstream are [quarter-pixel motion](https://en.wikipedia.org/wiki/Quarter-pixel_motion). Thus rescale is needed to first convert them to the pixel motion (*0.25) and then scale them according to the image size (multiple by mv_shape[0] / cvf["height"] or mv_shape[1] / cvf["width"]).

Regards,
Kai

**Comment by nemoHy** [comment]
Thanks for your reply!
